# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MWTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MWTest
  pod 'SnapKit'
  pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.902'
  pod 'Alamofire'
  #pod 'CHTCollectionViewWaterfallLayout/Swift'


  target 'MWTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MWTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
