/*
 * DO NOT EDIT.
 *
 * Generated by the protocol buffer compiler.
 * Source: edge.proto
 *
 */

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _1: SwiftProtobuf.ProtobufAPIVersion_1 {}
  typealias Version = _1
}

struct Bbproto_PEdgeVersion: SwiftProtobuf.Message {
  static let protoMessageName: String = _protobuf_package + ".PEdgeVersion"

  /// 是否强制更新的标志位
  var forceUpdate: Bool = false

  /// 是否推荐更新的标志位
  var recommendUpdate: Bool = false

  /// 是否通过应用商店更新的标志位
  var updateInAppStore: Bool = false

  /// 最新的版本号
  var latestVersion: String = String()

  /// 更新地址；UpdateInAppStore为true，就跳转到商店的下载页面；false时为apk下载地址
  var updateLink: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      switch fieldNumber {
      case 1: try decoder.decodeSingularBoolField(value: &self.forceUpdate)
      case 2: try decoder.decodeSingularBoolField(value: &self.recommendUpdate)
      case 3: try decoder.decodeSingularBoolField(value: &self.updateInAppStore)
      case 4: try decoder.decodeSingularStringField(value: &self.latestVersion)
      case 5: try decoder.decodeSingularStringField(value: &self.updateLink)
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.forceUpdate != false {
      try visitor.visitSingularBoolField(value: self.forceUpdate, fieldNumber: 1)
    }
    if self.recommendUpdate != false {
      try visitor.visitSingularBoolField(value: self.recommendUpdate, fieldNumber: 2)
    }
    if self.updateInAppStore != false {
      try visitor.visitSingularBoolField(value: self.updateInAppStore, fieldNumber: 3)
    }
    if !self.latestVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.latestVersion, fieldNumber: 4)
    }
    if !self.updateLink.isEmpty {
      try visitor.visitSingularStringField(value: self.updateLink, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "bbproto"

extension Bbproto_PEdgeVersion: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "ForceUpdate"),
    2: .same(proto: "RecommendUpdate"),
    3: .same(proto: "UpdateInAppStore"),
    4: .same(proto: "LatestVersion"),
    5: .same(proto: "UpdateLink"),
  ]

  func _protobuf_generated_isEqualTo(other: Bbproto_PEdgeVersion) -> Bool {
    if self.forceUpdate != other.forceUpdate {return false}
    if self.recommendUpdate != other.recommendUpdate {return false}
    if self.updateInAppStore != other.updateInAppStore {return false}
    if self.latestVersion != other.latestVersion {return false}
    if self.updateLink != other.updateLink {return false}
    if unknownFields != other.unknownFields {return false}
    return true
  }
}
